options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'europe-west1'

steps:
# --- Build & Deploy start_pipeline ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/start_pipeline:latest', './cloud-run/start_pipeline']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/start_pipeline:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: gcloud
  args: [
    'run','deploy','start-pipeline',
    '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/start_pipeline:latest',
    '--region','${_REGION}',
    '--platform','managed',
    '--service-account','clippy-uppy-sa@$PROJECT_ID.iam.gserviceaccount.com',
    '--execution-environment','gen2',
    '--no-allow-unauthenticated',
    '--concurrency','20',
    '--cpu','1',
    '--memory','1Gi'
  ]

# --- Build & Deploy transcode ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/transcode:latest', './cloud-run/transcode']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/transcode:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: gcloud
  args: [
    'run','deploy','transcode-service',
    '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/transcode:latest',
    '--region','${_REGION}',
    '--platform','managed',
    '--service-account','clippy-uppy-sa@$PROJECT_ID.iam.gserviceaccount.com',
    '--execution-environment','gen2',
    '--no-allow-unauthenticated',
    '--max-instances','10',
    '--concurrency','2',
    '--cpu','2',
    '--memory','2Gi'
  ]

# --- Build & Deploy transcribe ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/transcribe:latest', './cloud-run/transcribe']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/transcribe:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: gcloud
  args: [
    'run','deploy','transcribe-service',
    '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/transcribe:latest',
    '--region','${_REGION}',
    '--platform','managed',
    '--service-account','clippy-uppy-sa@$PROJECT_ID.iam.gserviceaccount.com',
    '--execution-environment','gen2',
    '--no-allow-unauthenticated',
    '--max-instances','20',
    '--concurrency','5',
    '--cpu','2',
    '--memory','2Gi'
  ]

# --- Build & Deploy sample_frames ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/sample_frames:latest', './cloud-run/sample_frames']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/sample_frames:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: gcloud
  args: [
    'run','deploy','sample-frames-service',
    '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/sample_frames:latest',
    '--region','${_REGION}',
    '--platform','managed',
    '--service-account','clippy-uppy-sa@$PROJECT_ID.iam.gserviceaccount.com',
    '--execution-environment','gen2',
    '--no-allow-unauthenticated',
    '--max-instances','20',
    '--concurrency','5',
    '--cpu','2',
    '--memory','2Gi'
  ]

# --- Build & Deploy getty_ingestor ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/getty_ingestor:latest', './cloud-run/getty_ingestor']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/getty_ingestor:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: gcloud
  args: [
    'run','deploy','getty-ingestor-service',
    '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/getty_ingestor:latest',
    '--region','${_REGION}',
    '--platform','managed',
    '--service-account','clippy-uppy-sa@$PROJECT_ID.iam.gserviceaccount.com',
    '--execution-environment','gen2',
    '--no-allow-unauthenticated',
    '--max-instances','50',
    '--concurrency','30',
    '--cpu','1',
    '--memory','1Gi',
    '--set-env-vars','GETTY_API_KEY=r94mr4tht9hkpj86b94hag3p,GETTY_API_SECRET=yceVfv9XJAgfWcJLMLj7,START_PIPELINE_URL=https://start-pipeline-863025961248.europe-west1.run.app'
  ]

# --- Build & Deploy gemini_enricher ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/gemini_enricher:latest', './cloud-run/gemini_enricher']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/gemini_enricher:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: gcloud
  args: [
    'run','deploy','gemini-enricher-service',
    '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/gemini_enricher:latest',
    '--region','${_REGION}',
    '--platform','managed',
    '--service-account','clippy-uppy-sa@$PROJECT_ID.iam.gserviceaccount.com',
    '--execution-environment','gen2',
    '--no-allow-unauthenticated',
    '--max-instances','50',
    '--concurrency','30',
    '--cpu','1',
    '--memory','1Gi'
  ]

# --- Build & Deploy store_metadata ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/store_metadata:latest', './cloud-run/store_metadata']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/store_metadata:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: gcloud
  args: [
    'run','deploy','store-metadata-service',
    '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/store_metadata:latest',
    '--region','${_REGION}',
    '--platform','managed',
    '--service-account','clippy-uppy-sa@$PROJECT_ID.iam.gserviceaccount.com',
    '--execution-environment','gen2',
    '--no-allow-unauthenticated',
    '--max-instances','50',
    '--concurrency','50',
    '--cpu','1',
    '--memory','1Gi'
  ]

# ---------------------------------------------------------
# Batch Runner (Cloud Run Job)
# ---------------------------------------------------------
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/batch-runner", "batch-runner"]

- name: gcr.io/cloud-builders/docker
  args: ["push", "gcr.io/$PROJECT_ID/batch-runner"]

- name: gcr.io/cloud-builders/gcloud
  args:
    [
      "run", "jobs", "deploy", "batch-runner",
      "--image", "gcr.io/$PROJECT_ID/batch-runner",
      "--region", "europe-west1",
      "--set-env-vars", "BUCKET=df-films-assets-euw1",
      "--set-env-vars", "FOLDER=newsflare/newsflare_upload/",
      "--set-env-vars", "START_PIPELINE_URL=https://start-pipeline-863025961248.europe-west1.run.app/run_all",
      "--set-env-vars", "COUNT=20"
    ]

images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/start_pipeline:latest'
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/transcode:latest'
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/transcribe:latest'
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/sample_frames:latest'
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/getty_ingestor:latest'
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/gemini_enricher:latest'
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/clippyuppy/store_metadata:latest'
