steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/batch-runner", "batch-runner"]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/batch-runner"]

  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run", "jobs", "deploy", "batch-runner",
        "--image", "gcr.io/$PROJECT_ID/batch-runner",
        "--region", "europe-west1",
        "--set-env-vars", "BUCKET=df-films-assets-euw1",
        "--set-env-vars", "FOLDER=newsflare/",
        "--set-env-vars", "START_PIPELINE_URL=https://start-pipeline-863025961248.europe-west1.run.app/run_all",
        "--set-env-vars", "COUNT=5"
      ]
